### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by Rika-chan** [sekaiproject/ponscripter-fork#82]
I believe the SDL deps were included, but it appears to be having issues compiling it?

Debian Jessie is the OS

```
rika-chan@Homunyan:~/Downloads/ponscripter-fork-master$ make
make -C src all
make[1]: Entering directory '/home/rika-chan/Downloads/ponscripter-fork-master/src'
g++ -c  -Wall -DUSE_X86_GFX -O3 -fomit-frame-pointer -pipe -Wpointer-arith   -Iextlib/include  -I/usr/include/SDL2 -D_REENTRANT -I/home/rika-chan/Downloads/ponscripter-fork-master/src/extlib/include -I/home/rika-chan/Downloads/ponscripter-fork-master/src/extlib/include/smpeg2 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/freetype2 -DLINUX -DUSE_OGG_VORBIS   -DENABLE_JOYSTICK Ponscripter.cpp
In file included from ScriptParser.h:34:0,
                 from PonscripterLabel.h:30,
                 from Ponscripter.cpp:26:
AnimationInfo.h:34:23: fatal error: SDL_image.h: No such file or directory
 #include <SDL_image.h>
                       ^
compilation terminated.
Makefile.ponscripter:61: recipe for target 'Ponscripter.o' failed
make[1]: *** [Ponscripter.o] Error 1
make[1]: Leaving directory '/home/rika-chan/Downloads/ponscripter-fork-master/src'
Makefile:22: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Rika-chan** [comment]
Strangely, on a bare arch VM it compiles fine.

**Comment by euank** [comment]
In a clean debian jessie image (`docker run -it debian:jessie`), I was able to build successfully by cloning master and running the following:
```
apt-get update && apt-get install -y build-essential automake libasound2-dev
pushd ./src/extlib/src/SDL2_image-2.0.0/; sh fix-timestamps.sh; popd
./configure --with-internal-libs --with-internal-sdl
make
```
I suspect the `fix-timestamps.sh` bit is what was missing. You don't need to run that if you have a quite recent aclocal (why it might have worked on arch). If it still doesn't work with that, make sure you're on a fresh clone as a failed build can leave behind artifacts that affect future ones too sometimes iirc.

**Comment by Rika-chan** [comment]
Makes fine, now.

Appears to have issues with loading images, I believe I saw another issue about that.

**Comment by DanielOaks** [comment]
What sort of issues are those? I know Narci2 has some black screens, but if you have anything for us to test and work out, could be useful.

**Comment by Rika-chan** [comment]
@DanielOaks #83
