### ISSUE TITLE
Narcissu 1st & 2nd Glitch - No Sound

### ISSUE THREAD

**Issue by TheRango** [sekaiproject/ponscripter-fork#84]
It was playing with sound earlier but now it's completely stopped, I can hear songs on the Internet and there's sound on other games but on Narcissu there is no sound what so ever, I don't know if this is a glitch or my stupidity, please help.

**Comment by TheRango** [comment]
Never mind, I clicked M which is mute on this game. Haha, nice game btw, thanks for making it free.

**Comment by DanielOaks** [comment]
Someone else had this issue as well. It may be a good idea for us to have some notification that mute mode has been enabled.

Glad it got resolved! Let us know if you find anything else.
