### ISSUE TITLE
"quake" cmds don't quake

### ISSUE THREAD

**Issue by UncleMion** [sekaiproject/ponscripter-fork#87]
The "quake", "quakex", and "quakey" cmds should produce a screen-shaking effect, but don't.
I'm guessing it's related to the SDL2 update.
I wonder if some of the default numbered effects used in "effect" etc. may be broken as well but haven't tested yet.

**Comment by UncleMion** [comment]
I'm intending to tackle this issue myself, but if you already have an idea of how to fix it then by all means do so.

**Comment by DanielOaks** [comment]
Yeah, that effect code was put in before the SDL2 update and hasn't gotten
much love since. Most of the SDL2 work was done by @euank, but I'll take a
quick look and see if anything jumps out at me.

**Comment by UncleMion** [comment]
It seems like there _should_ be an efficient way to do the quake on the GPU end, considering it keeps the screen image static while performing the effect, just offsets it. But I don't know how GPUs handle that.

**Comment by UncleMion** [comment]
I've confirmed that numbered effects don't work either. I'll look at the dll-based code, that must have the SDL2 stuff.

**Comment by DanielOaks** [comment]
Hmm, thanks. I ported them almost directly from Onscripter-EN quite a while
ago (and Narcissu doesn't use much/any effects iirc), so it makes sense.
I'll take a look tonight when I get home, keep me posted!

**Comment by DanielOaks** [comment]
Offtopic: Might be good to include some/some more example files, ones that
just run through the effects to easily test them out, especially since that
spot of code isn't tested as much.

**Comment by UncleMion** [comment]
That sounds reasonable. I'll try to get an effect test script together.
Say, do you folks need a copy of the *NScr Command Reference? I've got the XML version I made some time back, but the XML/XSLT doesn't seem to behave very well with modern browsers. I should be able to generate an html file at least. May add your steam-related cmds at some point too :)

**Comment by DanielOaks** [comment]
Awesome, will keep an eye out.

I've tended to use the Reference on your site thus far. Could be useful to
throw the source files for it on Github? :)

**Comment by UncleMion** [comment]
Well the fix was simple, just took a while for me to relearn the code well enough to find the problem.
(The class and method names in this project can be highly confusing, I know. I'll see what else may have gotten broken unknowingly.)
I'll put together that quick effect test script once I relearn enough *nscr scripting for the job.
